In [1]:
import numpy as np

def probability(x, p):
    x = np.array(x)
    p = np.array(p)
    y = np.random.rand()

    cdf = np.cumsum(p)
    total = len(x)

    pos = 0

    for n in range(total - 1):
        pos = pos + (y >= cdf.item(n))

    return x.item(pos)

In [2]:
def creategraph(total_nodes, pro_edges, weights):
    source = np.array([])
    target = np.array([])
    weight = np.array([])

    for i in range(total_nodes):
        for k in range(total_nodes):
            if k == i:
                continue

            p = 1 - pro_edges
            has_edge = probability([0, 1], [p, pro_edges])

            if not has_edge:
                continue

            probabilities = np.zeros(len(weights))
            probabilities = probabilities + (1 / len(weights))
            w = probability(weights, probabilities)

            source = np.append(source, i)
            target = np.append(target, k)
            weight = np.append(weight, w)
    
    print(source)
    print(target)
    print(weight)
    
    return 1

creategraph(5, .65, [1, 2, 3, 4, 5])

[ 0.  0.  0.  0.  1.  1.  2.  3.  3.  4.  4.  4.  4.]
[ 1.  2.  3.  4.  0.  2.  3.  0.  4.  0.  1.  2.  3.]
[ 1.  2.  4.  1.  4.  2.  1.  4.  1.  4.  1.  2.  5.]


1